#ifndef UI_CONSTANTS_HPP
#define UI_CONSTANTS_HPP

enum class State
{
  STATE_MENU_SCREEN,
  STATE_INPUT_SCREEN,
  STATE_TRAINING_SCREEN,

  STATE_END
};

enum class ModelType
{
  MODEL_UNIVARIATE_LINEAR_REGRESSION,
  MODEL_MULTIPLE_LINEAR_REGRESSION,

  MODEL_END
};

#endif // UI_CONSTANTS_HPP